version: '3'
services:
  coordinate:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    volumes:
      - ./ik-6.3.0:/usr/share/elasticsearch/plugins/ik
    environment:
      - cluster.name=lxc_es
      - node.name=coordinate_node
      - node.master=false
      - node.data=false
      - node.ingest=false
      - transport.tcp.port=9303
      - http.port=9203
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
      - "discovery.zen.ping.unicast.hosts=${ip}:9302"
    ports:
      - 9203:9203
      - 9303:9303
    restart: always