version: '3'
services:
  data:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    volumes:
      - ./ik-6.3.0:/usr/share/elasticsearch/plugins/ik
    environment:
      - cluster.name=lxc_es
      - node.name=data_node
      - node.master=false
      - node.data=true
      - node.ingest=false
      - transport.tcp.port=9302
      - http.port=9202
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
      - "discovery.zen.ping.unicast.hosts=${ip}:9301"
    network_mode: "host"
    restart: always