version: '3'
services:
  master:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    volumes:
      - ./ik-6.3.0:/usr/share/elasticsearch/plugins/ik
    environment:
      - cluster.name=lxc_es
      - node.name=master_node
      - node.master=true
      - node.data=false
      - node.ingest=false
      - transport.tcp.port=9301
      - http.port=9201
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    network_mode: "host"
    restart: always